name: Aweek
version: '${version}'
main: org.apo.aweek.Aweek
api-version: '1.20'
author: APO2073
depend:
  - PlaceholderAPI
commands:
  joke:
    description: Smile!
    permission: Aweek.joke
    usage: /joke [Something :) ]
  aweek:
    description: Aweek default command
    permission: Aweek.aweek
    aliases:
      - Aw
    usage: /aweek [] ...